channels:
- conda-forge
dependencies:
- python=3.11.7
- pip<=23.3.1
- pip:
  - mlflow==2.6.0
  - astunparse==1.6.3
  - cloudpickle==2.2.1
  - numpy==1.26.3
  - optree==0.11.0
  - torch==2.4.1
  - tqdm==4.65.0
name: mlflow-env
